apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: custom-metrics-blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      custom: metrics
  template:
    metadata:
      labels:
        custom: metrics
    spec:
      hostNetwork: true
      containers:

      - name: blackbox-exporter
        image: prom/blackbox-exporter:latest
        ports:
          - name: http-metrics
            containerPort: 9115
        readinessProbe:
          httpGet:
            path: /
            port: 9115
          initialDelaySeconds: 5
          timeoutSeconds: 5

      - name: prometheus-to-sd-to-blackbox-exporter-proxy
        image: ruby:latest
        ports:
          - name: proxy
            containerPort: 8081
        env:
          - name: BLACKBOX_EXPORTER_HOST
            value: localhost:9115
        command:
            - /bin/sh
            - -c
            - |
              ruby -- <<-EOF

              require 'uri'
              require 'webrick'

              host = ENV['BLACKBOX_EXPORTER_HOST'] or raise "BLACKBOX_EXPORTER_HOST not set."
              port = ENV['PORT'] || 8081

              server = WEBrick::HTTPServer.new Port: port

              server.mount_proc '/' do |req, res|
                _, probe, mod, *url = req.unparsed_uri.split("/")

                mod    = mod
                target = url.join("/")

                require 'net/http'
                uri      = URI("http://#{host}/probe?target=#{target}&module=#{mod}")
                body     = Net::HTTP.get(uri)
                res.body = body
              end

              trap 'INT'  do server.shutdown end
              trap 'TERM' do server.shutdown end

              server.start
              EOF

      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.8.0
        ports:
          - name: profiler
            containerPort: 6061
        command:
          - /monitor
          - --source=blackbox-exporter:http://localhost:8081/probe/http_2xx/google.com
          - --stackdriver-prefix=custom.googleapis.com
          - --pod-id=$(POD_NAME)
          - --namespace-id=$(POD_NAMESPACE)
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
