version: '3'
services:
  prometheus: 
    image: prom/prometheus:latest
    links:
      - blackbox-exporter
    volumes:
      - "./blackbox-exporter/prometheus:/prometheus/config"
    command: >
      --storage.tsdb.path=/prometheus 
      --web.console.libraries=/etc/prometheus/console_libraries 
      --web.console.templates=/etc/prometheus/consoles
      --config.file=/prometheus/config/prometheus.yml 
    ports:
      - 9090:9090

  blackbox-exporter: 
    image: prom/blackbox-exporter:latest
    ports:
      - 9115
      
  prometheus-to-sd:
    image: gcr.io/google-containers/prometheus-to-sd:v0.3.2
    links:
      - blackbox-exporter
    command: >
      /monitor
      --stackdriver-prefix=custom.googleapis.com
      --source=machine:http://blackbox-exporter:9115/probe
