version: '3'
services:
  prometheus: 
    image: prom/prometheus:latest
    links:
      - blackbox-exporter
    volumes:
      - "./blackbox-exporter/prometheus:/prometheus/config"
    command: >
      --storage.tsdb.path=/prometheus 
      --web.console.libraries=/etc/prometheus/console_libraries 
      --web.console.templates=/etc/prometheus/consoles
      --config.file=/prometheus/config/prometheus.yml 
    # --web.listen-address="0.0.0.0:9090"
    ports:
      - 9090:9090

  blackbox-exporter: 
    image: prom/blackbox-exporter:latest
    ports:
      - 9115
      
